services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: organizacao_recursos
      POSTGRES_USER: organizacao
      POSTGRES_PASSWORD: organizacao
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
